build:
  maxIssues: 1000

config:
  warningsAsErrors: true

complexity:
  active: false

style:
  active: false

empty-blocks:
  active: false

exceptions:
  active: false

naming:
  active: false

performance:
  active: false

potential-bugs:
  active: false

formatting:
  # always disable:
  PackageName:
    active: false
  TrailingCommaOnCallSite:
    active: false
  TrailingCommaOnDeclarationSite:
    active: false

  # details configuring:
  MaximumLineLength:
    active: true
    maxLineLength: 140
  ArgumentListWrapping:
    active: true
    maxLineLength: 140
  ParameterListWrapping:
    active: true
    maxLineLength: 140
  PropertyWrapping:
    active: true
    maxLineLength: 140
  Wrapping:
    active: true
    maxLineLength: 140
