build:
  maxIssues: 1000

config:
  warningsAsErrors: true

complexity:
  active: false

style:
  active: false

empty-blocks:
  active: false

exceptions:
  active: false

naming:
  active: false

performance:
  active: false

potential-bugs:
  active: false
